version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-admin}
    volumes:
      - mongodb_data:/data/db

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # API service
  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: library-api
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=mongodb://root:admin@mongodb:27017/library-management
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  mongodb_data:
  redis_data:
